name: Edit on Tailscale SSH

on:
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  edit:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --auth-key=${{ secrets.TS_AUTH_KEY }} --ssh
      - name: Wait until done
        run: while true; do [[ -f "./done" ]] && echo "done file found" && break || sleep 10; done && rm done
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
