name: Install dependencies

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup environment
        run: |
          npm install -g pnpm
      - name: Install dependencies
        run: pnpm add -D daisyui
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
